---
name: Check

on:
  workflow_dispatch:
  pull_request:

jobs:   
  build:    
    runs-on: ubuntu-20.04           
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Lint with golangci-lint
      uses: golangci/golangci-lint-action@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Run GoReleaser check
      uses: goreleaser/goreleaser-action@v2.8.1
      with:
        version: latest
        args: build --skip validate 
